# 校验节点软件系统及硬件系统、安装必要基础组件、docker、kubeadm、kubelet、kubectl
- hosts: 
  - all
  roles:
  - prepare/base
  - prepare/docker
  - prepare/kubernetes

# 进行apiserver负载均衡
- hosts: 
  - lb
  roles:
  - { role: lb, when: "(groups['kube-master']|length + groups['new-master']|length) > 1 and lb_mode != 'slb'" }

# 安装etcd，并分发etcd证书到master节点
- hosts: 
  - etcd
  - kube-master
  roles:
  - etcd

# 生成master节点证书，初始化master节点
- hosts: 
  - kube-master
  roles:
  - kube-master

# 初始化worker节点
- hosts: 
  - kube-worker
  roles:
  - kube-worker

# 标记各节点角色
- hosts: 
  - all
  roles:
  - post

# 安装基础插件
- hosts: 
  - kube-master
  roles:
  - { role: addons/flannel, when: cluster_network =='flannel' }
  - { role: addons/ingress-nginx }
  - { role: addons/metrics-server }
  - { role: addons/kubernetes-dashboard }