- block:
  - name: 在第一台 master 节点创建 ingress-nginx 配置文件目录
    file:
      path: /etc/kubernetes/addons/ingress-nginx
      state: directory

  - name: 渲染 ingress-nginx 配置文件
    template:
      src: ingress-nginx.yaml.j2
      dest: /etc/kubernetes/addons/ingress-nginx/ingress-nginx.yaml
    register: ingress_nginx_manifest

  - name: 部署 ingress-nginx
    command: kubectl apply -f /etc/kubernetes/addons/ingress-nginx/ingress-nginx.yaml
    when: ingress_nginx_manifest.changed

  - name: 轮询等待 ingress-nginx 运行
    shell: kubectl get pod --all-namespaces -o wide | grep 'nginx-ingress' | awk '{print $4}'
    register: pod_status
    until: "'Running' in pod_status.stdout"
    retries: 60
    delay: 5
    ignore_errors: true

  when: inventory_hostname == groups['kube-master']|first