- name: 添加 Docker yum 仓库
  yum_repository:
    name: docker-ce
    description: Docker Repository
    baseurl: "{{ docker_yum_repo }}"
    enabled: no
    gpgcheck: no
    state: present

- name: 安装 Docker
  yum:
    name: "docker-ce-{{ docker_version }}.ce"
    state: present
    enablerepo: docker-ce