- block:
  - name: 取消 master taint，使 master 节点可以调度
    shell: "kubectl taint nodes {{inventory_hostname}} node-role.kubernetes.io/master-"
    delegate_to: "{{ groups['kube-master']|first }}"
    ignore_errors: yes
    
  - name: 设置 worker 节点 role
    shell: "kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker='' --overwrite"
    delegate_to: "{{ groups['kube-master']|first }}"
    ignore_errors: true
  when: (inventory_hostname in groups['kube-master'] and inventory_hostname in groups['kube-worker']) or
        (inventory_hostname in groups['kube-master'] and inventory_hostname in groups['new-worker'])  or
        (inventory_hostname in groups['new-master']  and inventory_hostname in groups['new-worker'])

- name: 设置 lb 节点 role
  shell: "kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/lb='' --overwrite"
  delegate_to: "{{ groups['kube-master']|first }}"
  ignore_errors: true
  when:  
  - lb_mode == "haproxy"
  - inventory_hostname in groups['lb'] 

- name: 设置 etcd 节点 role
  shell: "kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/etcd='' --overwrite"
  delegate_to: "{{ groups['kube-master']|first }}"
  ignore_errors: true
  when: inventory_hostname in groups['etcd']