- name: 创建 admin.conf 配置文件
  shell: >
    cd /etc/kubernetes/pki/ &&
    kubectl config set-cluster kubernetes 
    --certificate-authority=ca.crt 
    --embed-certs=true 
    --server=https://{{ KUBE_APISERVER_IP | trim }}:{{ KUBE_APISERVER_PORT | trim }} 
    --kubeconfig=/etc/kubernetes/admin.conf &&
    kubectl config set-credentials kubernetes-admin
    --client-certificate=admin.crt
    --client-key=admin.key 
    --embed-certs=true 
    --kubeconfig=/etc/kubernetes/admin.conf &&
    kubectl config set-context kubernetes-admin@kubernetes 
    --cluster=kubernetes 
    --user=kubernetes-admin
    --kubeconfig=/etc/kubernetes/admin.conf &&
    kubectl config use-context 
    kubernetes-admin@kubernetes 
    --kubeconfig=/etc/kubernetes/admin.conf

- name: 创建 controller-manager.conf 配置文件
  shell: >
    cd /etc/kubernetes/pki/ &&
    kubectl config set-cluster kubernetes 
    --certificate-authority=ca.crt 
    --embed-certs=true 
    --server=https://{{ KUBE_APISERVER_IP | trim }}:{{ KUBE_APISERVER_PORT | trim }} 
    --kubeconfig=/etc/kubernetes/controller-manager.conf &&
    kubectl config set-credentials system:kube-controller-manager 
    --client-certificate=kube-controller-manager.crt 
    --client-key=sa.key 
    --embed-certs=true 
    --kubeconfig=/etc/kubernetes/controller-manager.conf &&
    kubectl config set-context system:kube-controller-manager@kubernetes 
    --cluster=kubernetes 
    --user=system:kube-controller-manager 
    --kubeconfig=/etc/kubernetes/controller-manager.conf &&
    kubectl config use-context system:kube-controller-manager@kubernetes 
    --kubeconfig=/etc/kubernetes/controller-manager.conf

- name: 创建 scheduler.conf 配置文件
  shell: >
    cd /etc/kubernetes/pki/ &&
    kubectl config set-cluster kubernetes 
    --certificate-authority=ca.crt 
    --embed-certs=true 
    --server=https://{{ KUBE_APISERVER_IP | trim }}:{{ KUBE_APISERVER_PORT | trim }} 
    --kubeconfig=/etc/kubernetes/scheduler.conf &&
    kubectl config set-credentials system:kube-scheduler 
    --client-certificate=kube-scheduler.crt
    --client-key=kube-scheduler.key 
    --embed-certs=true 
    --kubeconfig=/etc/kubernetes/scheduler.conf &&
    kubectl config set-context system:kube-scheduler@kubernetes 
    --cluster=kubernetes 
    --user=system:kube-scheduler 
    --kubeconfig=/etc/kubernetes/scheduler.conf &&
    kubectl config use-context system:kube-scheduler@kubernetes 
    --kubeconfig=/etc/kubernetes/scheduler.conf

- name: 创建 kubelet.conf 配置文件
  shell: >
    cd /etc/kubernetes/pki/ &&
    kubectl config set-cluster kubernetes 
    --certificate-authority=ca.crt 
    --embed-certs=true 
    --server=https://{{ KUBE_APISERVER_IP | trim }}:{{ KUBE_APISERVER_PORT | trim }} 
    --kubeconfig=/etc/kubernetes/kubelet.conf &&
    kubectl config set-credentials system:node:{{ inventory_hostname }} 
    --client-certificate=apiserver-kubelet-client.crt 
    --client-key=apiserver-kubelet-client.key 
    --embed-certs=true 
    --kubeconfig=/etc/kubernetes/kubelet.conf &&
    kubectl config set-context system:node:{{ inventory_hostname }}@kubernetes 
    --cluster=kubernetes --user=system:node:{{ inventory_hostname }} 
    --kubeconfig=/etc/kubernetes/kubelet.conf &&
    kubectl config use-context system:node:{{ inventory_hostname }}@kubernetes 
    --kubeconfig=/etc/kubernetes/kubelet.conf